spring:
  application:
    name: kotiln

  datasource:
    username: ${vault.user}
    password: ${vault.password}
    url: jdbc:mysql://127.0.0.1:3306/employees
    driver-class-name: com.mysql.cj.jdbc.Driver
